### ISSUE TITLE
Introduce a new regular expression operator for search arguments 

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#103] opened 2020-04-03 12:28 UTC
Currently Cenzontle search arguments offer the usage of a set of logical operators, e.g. `eq`, `gt`, `like` among others. Please extend this to include a new operator `regex`. This operator will match the selected field with a regular expression provided as `value` in the form of a string.

Example:
```
peopleConnection( 
  search: { field: name, operator: regex, value: { 
    value: "^[Hh]ello [Ww]orld$", type: "String" }
  }
)
```
Note that the above format of the regular expression might not be correct. See the respective Sequelize documentation for details.

### Tips

To implement this issue the following modules will have to be adjusted.
* `schemas/commons.js` in graphql-server is generated by `funks.js` in the code-generator
* `graphql-server/connection.js` in graphql-server declaration of available operators
* `./utils/search-argument.js` in graphql-server might need adjustment, too

Note that the above list might not be exhaustive.

**Comment by asishallab** [comment] 2020-04-06 11:12
The functionality you provide with this issue can only be tested efficiently with an integration test. That is a test, that uses the code-generators to setup a full working "Cenzontle graphql-server" with some test data models. Within this server test data is created and allows for testing the new `meta_query` function. The test should include:

* Combine multiple queries into one
* Query different data models
* Verify that only valid arguments (request post data) is accepted
* Verify that both `jq` and `jsonPath` expressions work

You can use the integration test file [`./test/mocha_integration_test.js`](https://github.com/ScienceDb/graphql-server-model-codegen/blob/master/test/mocha_integration_test.js). Please modify it as follows:
1. Remove test cases 8. and 18. as they test the deprecated vue-table functionality
2. Renumber the tests, so that we do not skip numbers, but leave room for 18.
3. What formerly was test 18. can be rewritten to hold your integration test of `meta_query`.

**Comment by tmvoe** [comment] 2020-04-08 09:23
The issue is resolved and the tests pass. All changes have been merged into master (in case of graphql-server-model-codegen and graphql-server) or i25-starter-pack-react (in case of the Starter pack).

Commits:
https://github.com/ScienceDb/graphql-server-model-codegen/commit/24eb6530f3386715cbabc8437b7fd12f51ab8a16
https://github.com/ScienceDb/graphql-server-model-codegen/commit/e7d5c552fd6a5df45be49d67d493552f78d9a31a
https://github.com/ScienceDb/graphql-server-model-codegen/commit/9dc4ffb2521b0724e2ccf930deb12d7f448da1d5
https://github.com/ScienceDb/graphql-server-model-codegen/commit/b39f09355b7bf560e63d2661a7b594444edb6240
https://github.com/ScienceDb/graphql-server-model-codegen/commit/81b85c27deda84f34d96f96bd56c7b46313fd1f2
https://github.com/ScienceDb/graphql-server-model-codegen/commit/60e00d827acb584ed607777620f5c93bc917723e
https://github.com/ScienceDb/graphql-server-model-codegen/commit/2be95b15f89073e87dd7a49a6c5f44b4bf03a39f
https://github.com/ScienceDb/graphql-server-model-codegen/commit/22a2be3c71d9b6c54a291040d86b55c4c9550dd2
https://github.com/ScienceDb/graphql-server-model-codegen/commit/ec5dc8dc8b77883ab37305f77c04783b0a94a773
https://github.com/ScienceDb/graphql-server-model-codegen/commit/0a09ef16683bb262f6033dfc89bcfb5e6909373f
https://github.com/ScienceDb/graphql-server-model-codegen/commit/0706ac3f0054999e38fa2c9dcbca4abd605e7e2f

**Closed** 2020-04-08 09:33 UTC
Labels: enhancement
